apiVersion:  extensions/v1beta1
kind:  Deployment
metadata:
  name:	nginx-deployment
spec:
  replicas:  5
  template:
    metadata:
      labels:
        app:  web_server
    spec:
      containers:
      - name:  nginx
        image:  nginx
